#coding:utf-8
#:import Toolbar kivymd.toolbar.Toolbar
#: import ThemeManager kivymd.theming.ThemeManager

<GerenciadorTela>:
	Tela:


<Tela>:
	BoxLayout:
		orientation:'vertical'
		Toolbar:
			id:toolbar
			title: "FDS"
			md_bg_color : app.theme_cls.primary_color
			background_palette : 'Primary'
			elevation: 10
			left_action_items:[['menu', lambda x:None]]
			background_hue: '500'
		
		BoxLayout:
		